### ISSUE TITLE
NPC's overlayed

### ISSUE THREAD

**Issue by milkev** [JavidPack/Census#5]
npc's at the 'inbetween' of moved in and not moved in are overlayed and neither are usually legible due to the words overlapping.
![image](https://user-images.githubusercontent.com/22010128/120084892-33fde400-c091-11eb-8f2c-5c806f6d9433.png)

EDIT: changing ui scale by 1% seems to fix it... but i dont really understand why i should have to do that in the first place

**Comment by JavidPack** [comment]
The Terraria code math is slightly off, reproducing the original bug would make ugly code, I was meaning to fix this in tmod itself, I'll try to remember.

But yeah, slightly adjusting the screen size or zoom works.
