### ISSUE TITLE
Localization for NPC Conditions

### ISSUE THREAD

**Issue by Destructor-Ben** [JavidPack/Census#9]
TownNPCInfo and Mod.Call should use LocalizedText so localization can be supported

**Comment by JavidPack** [comment]
They certainly should, especially when updated to 1.4.4. 

Another approach is if a string starting with a $ is passed in, interpret it as a translation key and use that. That's something that has been done with some of my other mods.

The current call code should be able to be extended to support string, $ string, and LocalizedText with no issues.

**Comment by JavidPack** [comment]
The v0.5 release, for 1.4.4 tModLoader, supports this now. In fact, modders don't even need to Mod.Call anymore, the keys will be added automatically.
